spring.application.name=ResumeAnalyser

server.port=${PORT:8080}

spring.datasource.url=jdbc:mariadb://resume-analyzer-oily-loom.sage.cloud.layerbase.dev:38222/resume_analyzer
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.thymeleaf.cache=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

server.servlet.session.timeout=30m

server.error.whitelabel.enabled=false